- src/sound/openal.c
- src/win/msvc15/global.props
Please merge only if the changes to openal.c do not break mingw builds.... In that case we can #ifdef them for MSVC
> Add/Fix OpenAL sound in the MSVC builds

- src/win/msvc15/VARCem.vcxproj
- src/win/msvc15/VARCem.vcxproj.filters
This PR updates the MSVC project files with the recent changes from upstream
> MSVC: Update project files

- src/video/vid_ati_mach64.c
- src/video/vid_bt485_ramdac.c
- src/video/vid_cga_comp.c
- src/video/vid_cl54xx.c
- src/video/vid_ega.c
- src/video/vid_et4000w32.c
- src/video/vid_herculesplus.c
- src/video/vid_incolor.c
- src/video/vid_s3.c
- src/video/vid_s3_virge.c
- src/video/vid_sdac_ramdac.c
- src/video/vid_stg_ramdac.c
- src/video/vid_svga.c
- src/video/vid_tgui9440.c
- src/win/win.c
- src/win/win.h
- src/win/win_cdrom_ioctl.c
- src/win/win_crashdump.c
- src/win/win_d3d.cpp
- src/win/win_dialog.c
- src/win/win_joystick.cpp
- src/win/win_new_floppy.c
- src/win/win_png.c
- src/win/win_settings.c
Here is the first of probably many commits that fix some warnings. It was rebased onto master and I made extra sure to change/fix all RCS IDs this time ;-)
For now it only covers the win/ and video/ directories, although I didn't dare to touch the voodoo.c file (I had all warnings fixed but the code I changed looked like it only worked by accident and I might have broken more than I fixed, so I left it for future-me - or future-anyone-else ;-)
> Some warning fixes

- src/win/VARCem.rc
- src/win/msvc15/VARCem.vcxproj
- src/win/msvc15/VARCem.vcxproj.filters
- src/win/msvc15/VARCem.vcxproj.user
Also add the user properties file that was missing so far
> MSVC: Update project file for sio/* and generate Manifest automatically

- src/cdrom/cdrom.c
- src/cdrom/cdrom_dosbox.cpp
- src/cdrom/cdrom_dosbox.h
- src/cpu/386.c
- src/cpu/386_common.h
- src/cpu/386_dynarec.c
- src/cpu/808x.c
- src/cpu/codegen_timing_pentium.c
- src/cpu/cpu.h
- src/cpu/x86seg.c
- src/cpu/x87_ops.h
Fix some more warnings in cpu/ and cdrom/
> Warning fixes

- src/win/msvc15/VARCem.vcxproj
- src/win/msvc15/VARCem.vcxproj.filters
Update project files for the recent lzf move and the nvr/rtc changes
> MSVC: Some files were moved again

- src/video/vid_svga_render.c
This is a compilation error (not a warning) on MSVC
> Video: Fix uninitialized variable

- src/game/gameport.c
- src/win/msvc15/VARCem.vcxproj
- src/win/msvc15/VARCem.vcxproj.filters
> Update MSVC project files

- src/disk/zip.c
- src/dma.c
- src/io.c
- src/keyboard_xt.c
- src/network/slirp/socket.c
- src/nvr_at.c
- src/pci.c
- src/pic.c
- src/pit.c
- src/scsi/scsi_disk.c
- src/scsi/scsi_ncr53c810.c
- src/scsi/scsi_x54x.c
- src/sound/filters.h
- src/sound/resid-fp/siddefs-fp.h
- src/sound/snd_emu8k.c
- src/sound/snd_lpt_dac.c
- src/sound/snd_lpt_dss.c
- src/sound/snd_sb.c
- src/video/vid_voodoo.c
MSVC can be quite picky ... Down to <300 warnings now (from almost 1000 at the beginning)
> Your daily dose of warning fixes

- src/sound/snd_dbopl.cpp
- src/win/msvc/vc15/VARCem.vcxproj
- src/win/msvc/vc15/VARCem.vcxproj.filters
Update the project files and fix a small compilation error that only showed up in MSVC
> MSVC fixes

- src/pc.c
- src/win/msvc/vc15/VARCem.vcxproj
- src/win/msvc/vc15/VARCem.vcxproj.filters
This time removing the ConformanceMode option (aka /permissive-) as it should not have been set from the beginning (the default is false, no idea when this got switched to true...)
> Semi-Regular MSVC project file update

- src/devices/video/vid_cl54xx.c
- src/devices/video/vid_svga.c
- src/devices/video/video.h
- src/devices/video/video_dev.c
Some Cirrus cards fixes : HW Cursor for 512Kb VRAM and Hi-Res SVGA 16 colors display.
> Adding Cirrus Logic GD5402 & GD5420

- src/win/msvc/vc16/VARCem.vcxproj
- src/win/msvc/vc16/VARCem.vcxproj.filters
- src/win/msvc/vc16/global.props
...also cleaned up import libraries to reduce link time, and added XInput to the list of libs to link against (for the joystick support)
> MSVC 2019 project updates

- src/devices/sound/snd_gus.c
IO port flexibility
256k, 512K, or 1 Mo total memory available
> Gus soundcard changes

- src/devices/video/vid_cl54xx.c
- src/devices/video/vid_ht216.c
- src/devices/video/vid_svga.c
- src/devices/video/vid_svga.h
Change the way extended latches are handled (may broke ht216)
Add AVGA2 timing and ID
fix broken mapping
fixed GD5446 with NT 5
Removed a hack about 512k cards.
> Cirrus fixes

- src/devices/sound/snd_cs423x.c
- src/devices/sound/snd_gus.c
removed an if condition that should not be there
fix Gus max being mute on Windows 3.11
> Gus small fixes

- src/machines/m_olim24_vid.c
Fixes issue #95
Add overscan to m24
> Fix Olivetti M24 black screen

- src/devices/chipsets/intel4x0.c
- src/devices/chipsets/neat.c
- src/devices/chipsets/scat.c
- src/devices/chipsets/sis471.c
- src/devices/chipsets/sis496.c
- src/machines/m_ali.c
- src/machines/m_sis471.c
Add Sis 471 cache and shadow bios functions
Add cpu cache for Sis 496 / Intel Chipsets
Changes to default memory limit for Ali 1429 & Sis 471 machines
Code cleanup in neat and scat.c
> Chipsets improvements

- src/devices/video/vid_voodoo.c
- src/win/win_settings_video.h
Latch Voodoo vertices at the start of triangle_setup() before sorting to prevent any races.
Tweak Voodoo swap pending code.
> Voodoo fixes

- src/devices/video/vid_s3.c
- src/devices/video/vid_sdac_ramdac.c
- src/devices/video/video.h
- src/devices/video/video_dev.c
Fix clock selection on S3 Vision864 with SDAC
Fix reads of 3C6 on SDAC when not returning command register on RAMDAC
ID.
> S3 video cards fixes and addition

- src/devices/video/vid_s3.c
- src/devices/video/vid_sdac_ramdac.c
- src/devices/video/video.h
- src/devices/video/video_dev.c
- src/machines/m_intel4x0.c
- src/machines/machine.h
- src/machines/machine_table.c
Remove VLB bus and PS2 port for revenge/plato intel boards cause they have none.
> Add Ambra machines based on Intel boards

- src/devices/scsi/scsi.c
- src/devices/scsi/scsi_aha154x.c
- src/devices/scsi/scsi_aha154x.h
- src/devices/scsi/scsi_buslogic.c
- src/devices/scsi/scsi_buslogic.h
- src/devices/scsi/scsi_x54x.h
> Add Adaptec AHA-1540A & BusLogic BT-542B

- src/cpu/x86seg.c
> Applied pcem commit #d89c120

- src/devices/floppy/fdc.c
- src/devices/floppy/fdc.h
- src/machines/m_ali.c
- src/machines/m_tandy1000.c
Fix ALI-1429 nvr size : fixes issue #135 
Apply Tandy 1000SL2 floppy fix from upstream
> Small fixes

- src/devices/chipsets/sis496.c
- src/devices/scsi/scsi_aha154x.c
- src/devices/scsi/scsi_buslogic.c
- src/devices/scsi/scsi_x54x.c
- src/devices/scsi/scsi_x54x.h
- src/machines/m_asus.c
Update Sis496
Remove VLB on Asus boards
Fix SCSI BT445S & 545S BIOS loading broken by commit 504e618
> Some small fixes & updates

- src/devices/scsi/scsi_aha154x.c
- src/devices/scsi/scsi_x54x.c
- src/devices/scsi/scsi_x54x.h
> More SCSI fixes

- src/devices/chipsets/vl82c480.c
- src/machines/m_ps1.c
from upstream
Fix HP Vectra 486
> Apply VLSI 480 update

- src/cpu/x87_ops_misc.h
- src/devices/sound/snd_gus.c
from upstream.
GUS should set DMA TC IRQ flag even when IRQ disabled.
Correct top-of-stack value store by FSTENV
FSCALE should always return 0.0 if ST(0) input is 0.0
> Apply some fixes

- src/devices/chipsets/opti895.c
- src/devices/sio/sio_fdc37c93x.c
- src/devices/video/vid_s3_virge.c
FDC37c93x fixes
Update Opti 895
Update S3 Virge
> Some update and fixes

- src/cpu/386.c
- src/cpu/386_common.h
- src/cpu/386_dynarec.c
- src/cpu/x86.h
- src/cpu/x86_ops_int.h
- src/cpu/x86_ops_ret.h
- src/cpu/x86seg.c
- src/devices/video/vid_paradise.c
- src/devices/video/vid_voodoo_banshee.c
- src/devices/video/video.h
- src/devices/video/video_dev.c
and add Voodoo3 as DEV devices
> Small CPU updates
